demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#from home import urls as home_urls
#from tweets import urls as tweets_urls
from tweets import views
from hashtags.views import HashTagView



urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include(home_urls)),
    path('', views.List_Tweet.as_view(), name="home"),
    path('tweet/', include("tweets.urls", namespace="tweet")),
    path('tags/<str:hashtag>/', HashTagView.as_view(), name="hashtag"),
    path('api/tweet/', include("tweets.api.urls", namespace="tweet-api")),
    path('accounts/', include("accounts.urls", namespace="user_profile")),
]



if settings.DEBUG:
	urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

demo/tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from tweets import views

app_name = 'tweets'

urlpatterns = [
	path('',RedirectView.as_view(url="/")),
	path('search', views.List_Tweet.as_view(), name="List_Tweet_view"),
	path('detail_tweet/<int:pk>/', views.Detail_Tweet.as_view(), name="Detail_Tweet_view"),
	path('detail_tweet/<int:pk>/retweet', views.ReTweetView.as_view(), name="ReTweet_view"),
	path('update_tweet/<int:pk>/', views.Update_Tweet.as_view(), name="Update_Tweet_view"),
	path('create_tweet/', views.Create_Tweet.as_view(), name="Create_Tweet_view"),
	path('delete_tweet/<int:pk>/', views.Delete_Tweet.as_view(), name="Delete_Tweet_view"),


	path('create_tweet2/', views.create_tweet, name="Create_Tweet_view2"),
]

demo/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->

    <link href="{% static  'bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>

    <style type="text/css">
        .red-color{
            color:red;
        }
        .black-color{
            color:black;
        }
        .grey-color{
            color:#ccc;
        }
    </style>

  </head>
  <body>
    
    {% include "navbar.html" %}
   
    <div class="container">
        {% block content %}
    
        {% endblock %}     
    </div>

    



   
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{% static 'bootstrap4/js/jquery.js' %}"></script>
    {% block script %} {% endblock %}
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->

    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->



    <script type="text/javascript">
        $(document).ready(function(){
            var typingTimer;
            var doneInterval = 300; // ms
            var searchInput = $("#nav-bar-form input[type=search]")
            var searchQuery;

            searchInput.keyup(function(event){
                searchQuery = $(this).val()

                clearTimeout(typingTimer)
                typingTimer = setTimeout(doneSearchingTyping, doneInterval)
               
            })

            searchInput.keydown(function(event){
              clearTimeout(typingTimer)  
            })


            function doneSearchingTyping(){
                if (searchQuery){
                    var url = "/tweet/search?q=" + searchQuery
                    document.location.href = url;
                }
            }

        });
    </script>











  </body>
</html>

demo/templates/navbar.html
<nav  class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">TweetDemo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form id="nav-bar-form" class="form-inline my-2 my-lg-0" method="GET" action="{% url 'tweets:List_Tweet_view' %}">
      <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>